#ifndef _ARDUINO_FACTORY_BRIDGE_CONSTANTS_H_
#define _ARDUINO_FACTORY_BRIDGE_CONSTANTS_H_

#include <Arduino.h>

#define BAUD_RATE 115200
#define PACKET_END '\n'
// #define DEBUG
#define ASYNCIO_ARDUINO_BRIDGE_SERIAL SerialUSB
// #define ARDUINO_RESETS_ON_CONNECT

#endif  // _ARDUINO_FACTORY_BRIDGE_CONSTANTS_H_
